### ISSUE TITLE
Group objects in changeset description

### ISSUE THREAD

**Issue by Zverik** [ppawel/openstreetmap-website#10]
When a user creates or modifies a lot of buildings, that changeset is visualized in history tab with a lot of brown boxes. A LOT -- like, 40 lines of brown boxes. Those should be grouped: "[  ] x 50", for example. Those pictograms should take no more than 5 lines ideally.

Example location: http://owl.apis.dev.openstreetmap.org/?lat=54.5072&lon=37.0733&zoom=13&layers=M (as of 14.01.2013).

**Comment by ppawel** [comment]
Good idea, thanks.

**Comment by ppawel** [comment]
I implemented aggregating and [ ] x 50 but that somehow defeats the purpose of those icons because you have to read the numbers. If someone adds a lot of buildings it should be easy to identify that at a quick glance I think. I will maybe add a max limit of icons like 10 of one tag - so for 50 buildings there would be 10 icons meaning there is "a lot" of buildings in this changeset.

**Comment by Zverik** [comment]
Yes, that will do too probably. The problem is not repetitions, but changeset descriptions spanning tens of lines.

**Comment by ppawel** [comment]
OK, I improved tag symbol handling. Let me know what you think (should be live within 1 hour).

**Comment by Zverik** [comment]
Yes, looks much better now. Thanks.
